blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using pd-agent
    url: https://github.com/projectdiscovery/pd-agent/discussions/categories/q-a
    about: Ask a question or request support for using pd-agent

  - name: Share idea / feature to discuss for pd-agent
    url: https://github.com/projectdiscovery/pd-agent/discussions/categories/ideas
    about: Share idea / feature to discuss for pd-agent

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication