blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using pdtm-agent
    url: https://github.com/projectdiscovery/pdtm-agent/discussions/categories/q-a
    about: Ask a question or request support for using pdtm

  - name: Share idea / feature to discuss for pdtm-agent
    url: https://github.com/projectdiscovery/pdtm-agent/discussions/categories/ideas
    about: Share idea / feature to discuss for pdtm-agent

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication